### ISSUE TITLE
how to point this abe to a local testnet

### ISSUE THREAD

**Issue by smatthewenglish** [c0achmcguirk/docker-bitcoin-abe#1]
I have run the testnet [c0achmcguirk/bitcoin-dev-box](https://github.com/c0achmcguirk/bitcoin-dev-box/) on my machine and successfully transfered coins between the two addresses there. 

now I'd like to export these transactions to a relational db using this abe container, however- I'm confused about the README command

```
docker run -d --name abe -P -p 49001:80 \ -v <PATH_TO_YOUR_BITCOIN_DIR>:/datadir poliver/bitcoin-abe
```

what will the BITCOIN_DIR look like? 

does anyone know what kind of file, i.e. the extension perhaps, should be in there? where it would be from the home directory of c0achmcguirk/bitcoin-dev-box/ or what the name of it is?

**Comment by c0achmcguirk** [comment]
I use [Bitcoin-QT](https://bitcoin.org/en/download) as a reference client to connect to my [bitcoin-dev-box](https://github.com/c0achmcguirk/bitcoin-dev-box) like this:

### Example on a Mac

```
$ mkdir -p ~/localnet
$ /Applications/Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt \
    -regtest -dnsseed=0 -connect=dockerhost:49020 \
    -datadir=./localnet/
```

### Example on Linux

```
$ mkdir -p ~/localnet
$ /path/to/bitcoin-qt \
    -regtest -dnsseed=0 -connect=localhost:49020 \
    -datadir=./localnet/
```

### Example on Windows

```
$ MKDIR $HOME\localnet
$ "C:\Program Files\Bitcoin\bitcoin-qt.exe" \
    -regtest -dnsseed=0 -connect=dockerhost:49020 \
    -datadir=$HOME/localnet
```

When that’s all set up, Bitcoin-QT will save the testnet entries in the folder specified by `-datadir` (the `localnet` folder in your home directory).

Then I boot up bitcoin-abe and point it to the testnet data dir:

### On a Mac.

```
$ docker run -d --name abe -P -p 49001:80 \
    -v ~/localnet:/datadir poliver/bitcoin-abe
```

Now bitcoin-abe has some data to work with...the bitcoin data saved by bitcoin-qt as it connects to the bitcoin nodes running on the bitcoin-dev-box.

### Exporting the data from bitcoin abe

As for exporting this to a relational database, the docker version of bitcoin-abe is using a sqlite file (`/datadir/abe.sqlite`). You could [copy that file to your local machine](http://stackoverflow.com/a/22050116/1229195) and connect to it using any number of tools. [This add-on for Firefox](https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/) is really nice…and you can export from the sqlite database easily too.

**Comment by s-matthew-english** [comment]
Hi Paul,

Do you know what the password is for the user '*tester*' on the docker
container?

I was trying to install bitcoin-qt with sudo apt-get but since I didn't
have the permission I finally just went with '*docker exec -u 0 -it
mycontainer bash*'.

Another problem I had was that I'm running this on a server- so I can't use
qt, I need something headless, so I went with bitcoind
<https://en.bitcoin.it/wiki/Bitcoind> and also bitcoin-cli, but- it sort
of- creating all kinds of problems.

Have you ever encountered difficulties when running the '*/path/to/bitcoin-qt
\ -regtest -dnsseed=0 -connect=localhost:49020 \ -datadir=./localnet/*'
maybe this only happens with bitcoind or bitcoin-cli?

It's complaining about "rpc password" and the "bitcoin.conf" file- that I
need to set a username there or something?

Sincerely,

Matthew

**Comment by smatthewenglish** [comment]
so- do you do that before or after your run the test net for the first time? 

when I do it- it seems that it's still trying to download the entire "real" bitcoin blockchain- on the bottom of the wallet program it says "7 years behind"

**Comment by c0achmcguirk** [comment]
Here's the order I do it in:
1. Run bitcoin-dev-box
2. (on bitcoin-dev-box) Start bitcoin-dev-box (`make start`)
3. (on bitcoin-dev-box) Generate 100 blocks so I have some bitcoins to send around (`make generate BLOCKS=100`)
4. (on bitcoin-dev-box) Get the address for node2: `make address2`
5. (on bitcoin-dev-box) Send some bitcoins: `make send address=<ADDRESS FROM STEP 4> AMOUNT=1.5`
6. (on bitcoin-dev-box) mine some blocks to confirm the transaction `make generate BLOCKS=3`
7. (from my local machine) load up a bitcoin client and have it talk to the docker-bitcoin-box as a server. I want the bitcoin client to save the database in `~/datadir`.
8. If everything works, you'll see a connection to the bitcoin network in the lower right of the bitcoin-qt client. (_see image below_). Remember to run the command where it stores its data in a new folder called `~/localnet/`. You may have to remove the folder before running bitcoin client, just to make sure.
9. Now that you have a bitcoin datadir working, bitcoin-abe can read the data for its web client. So start up bitcoin-abe... `docker run -d --name abe -P -p 49001:80 -v ~/localnet/regtest:/datadir poliver/bitcoin-abe`. **NOTE: The newer bitcoin clients store the testnet data in a subfolder of `/localnet` so I changed the command line to reflect that (`~/localnet/regtest:/datadir`)**

![connected](http://i.imgur.com/MtpsrhN.png)

**Comment by smatthewenglish** [comment]
what do you mean by "have it talk to the docker-bitcoin-box as a server." how to achieve that? is there some flag that I use to point it to sspecific port or ip address/localhost or something? 

also "I want the bitcoin client to save the database in ~/datadir."- but don't you specify with the earlier command that it saves the data in "./localnet/"

I still see in bitcoin-qt that it's missing "5 years of data" which doesn't make sense since I just started the container not more than 5 minutes ago- isn't it? 

it's right- I'm using Linux

**Comment by c0achmcguirk** [comment]
> what do you mean by "have it talk to the docker-bitcoin-box as a server." how to achieve that? is there some flag that I use to point it to sspecific port or ip address/localhost or something? 

That's in the command line, you have some parameters for bitcoin-qt that say it will connect to your docker-bitcoin-dev-box (instead of the regular bitcoin network). This is what the `-connect` parameter is for.

``` shell
# Running bitcoin-qt to talk to your local instance of bitcoin-dev-box
$ /path/to/bitcoin-qt -regtest -dnsseed=0 -connect=localhost:49020 -datadir=./localnet/
```

The **connect** parameter is the server address. If you leave it blank it will connect to the bitcoin network directly. In the case above it's going to connect to your bitcoin testnet running inside the docker container. It's connecting to `localhost:49020` which should be talking to the network inside the docker container if you mapped it to that port when you started **bitcoin-dev-box**.

This will only work if you start the bitcoin-dev-box with parameters that opened its port `19000` to your localhost `49020`:

``` shell
# Running bitcoin-dev-box, and mapping it's internal port 19000 to your localhost:49020
$ docker run -ti --name btcdev -P -p 49020:19000 poliver/bitcoin-dev-box
```

Notice how it's starting the docker box up and remapping your `localhost:49020` to port `19000` for the docker container? That's what you're connecting your bitcoin-qt client to.

> also "I want the bitcoin client to save the database in ~/datadir."- but don't you specify with the earlier command that it saves the data in "./localnet/"

With docker you have folders mapped to the dockerhost and those that are mapped locally inside the docker container. So that's probably where the confusion is coming from.

In this example for running bitcoin-abe:

``` shell
$ docker run -d --name abe -P -p 49001:80 -v ~/localnet/regtest:/datadir poliver/bitcoin-abe
```

This how things are mapped in the docker container and in your dockerhost.

| Dockerhost, Your Machine | Inside Docker Container (bitcoin-abe) |
| --- | --- |
| `Port 490001` | `Port 80` |
| `~/localnet/regtest` folder | `/datadir` folder |

Bitcoin-abe in the docker container wants it's data in a folder called `/datadir`. If you map it when you launch the container like the command above, you can allow the bitcoin-abe container to access your local hard drive. In this case, **inside** the bitcoin-abe container it's local `/datadir/` folder will be pointing to your `~/localnet/regtest/` folder.

> I still see in bitcoin-qt that it's missing "5 years of data" which doesn't make sense since I just started the container not more than 5 minutes ago- isn't it? 

That sounds like you're not talking to the _bitcoin-dev-box_ on your `localhost:49020`. Make sure the _bitcoin-dev-box_ is running and that port is open.

A good way to do this is run `docker ps` and look at the running containers:

``` shell
$ docker ps
CONTAINER ID  IMAGE                    PORTS                                                                        
e7dea5a0e410  poliver/bitcoin-dev-box  0.0.0.0:49020->19000/tcp, ....
```

I snipped a bunch out to make it fit, but the important thing is looking for the PORTS...you should see something like `49020 -> 19000` which shows that your local machine is properly redirecting traffic from `localhost:49020` to `bitcoin-dev-box:19000`.

**Comment by smatthewenglish** [comment]
I'm running arch not ubuntu- so I guess I can't build the docker image locally :/

so instead- since I have built the one from freewil/bitcoin-testnet-box, which I built locally, and ran with the command: 

docker run -ti --name btcdev -P -p 49020:19000 bitcoin-testnet-box

which was inspired by your advice of: 

```
bitcoin-dev-box, and mapping it's internal port 19000 to your localhost:49020
$ docker run -ti --name btcdev -P -p 49020:19000 poliver/bitcoin-dev-box
```

then I ran bitcoin-qt with the command: 

Running bitcoin-dev-box, and mapping it's internal port 19000 to your localhost:49020
$ docker run -ti --name btcdev -P -p 49020:19000 poliver/bitcoin-dev-box

but still it seems that it's not connecting to my local testnet, here's a screenshot

bitcoin-qt

![sss](https://cloud.githubusercontent.com/assets/9053984/16524848/16b5095e-3faa-11e6-85ca-0cb6eab7f6a9.png)

output of 'docker ps'

![zzz](https://cloud.githubusercontent.com/assets/9053984/16524856/1cc415ec-3faa-11e6-9dac-000690b1aa3c.png)

**Comment by smatthewenglish** [comment]
what do you think of the changes I made to the [bitcoin.conf files on my fork](https://github.com/s-matthew-english/bitcoin-dev-box/blob/master/hometester/testnet/2/bitcoin.conf)\- according to the answer to [this question](http://stackoverflow.com/questions/38095617/is-there-a-way-to-read-dat-files-as-in-the-storage-format-for-bitcoin-blocks)

**Comment by c0achmcguirk** [comment]
> I'm running arch not ubuntu- so I guess I can't build the docker image locally :/

I can't imagine why you couldn't build the docker image on arch--why is it giving you problems?

Also, why do you need to build it? Can't you just run `docker pull poliver/bitcoin-dev-box` and then run it?

> then I ran bitcoin-qt with the command: 

You didn't put the command you used to run bitcoin-qt? I think this is where you're having your troubles.

I have a Linux instance (Ubuntu 14.04) that is running headless, so I can't run bitcoin-qt on it...but I was able to connect to `poliver/bitcoin-dev-box` using the command from the dockerhost:

`bitcoind -regtest -dnsseed=0 -connect=localhost:49020 -datadir=./localnet`

It doesn't print anything to the screen, but I can see that it is populating the `~/localnet/regtest` folder on my Linux machine.

I then ran docker-bitcoin-abe (on the Linux box) like this:

`docker run -d --name abe -P -p 49001:80 -v ~/localnet/regtest:/datadir poliver/bitcoin-abe`

And a bitcoin-abe web site is running on my Linux box. Again, it's running headless on my machine, but I was able to browse bitcoin-abe using the _lynx_ web browser.

```
$ lynx localhost:49001

____ (BUTTON) Search
   Address or hash search requires at least the first 6 characters.

   Currency Code Block        Time          Started   Age (days) Coins Created Avg Coin Age   % CoinDD
   Testnet  BC0  120   2016-07-10 01:33:28 2011-02-02 1984.11    6050          16.4267      2.09629e-05%

   API (machine-readable pages)

   Powered by Abe Tips appreciated! BTC NMC
```

This is after I had the dev box running the server and I had generated 120 blocks using `make generate BLOCKS=120` on the _bitcoin-dev-box_.

### I think you're problem lies in how you are launching bitcoin-qt

I think everything else looks fine....assuming you have started your bitcoin nodes up by running `make start` on the _bitcoin-dev-box_.

You should launch bitcoin-qt (or bitcoind) _after_ the bitcoin-dev-box is launched and the server is running (run `make start`).

Launch it with the command line arguments like this:

`bitcoin-cli -regtest -dnsseed=0 -connect=localhost:49020 -datadir=./localnet`

or with **bitcoind**:

`bitcoind -regtest -dnsseed=0 -connect=localhost:49020 -datadir=./localnet`

> what do you think of the changes I made to the bitcoin.conf files on my fork- according to the answer to this question

Sorry Matthew, it's beyond my skill level. I just use bitcoin-abe to visualize the bitcoin data and it tells me everything I need to know.

With **bitcoin-abe** running in a docker container that sees my **bitcoin-qt** datadir, I can get the bitcoin-abe database by copying it from the docker container running **bitcoin-abe**:

`docker cp 7af0cde:/home/bitcoin-abe/abe.sqlite ~/abe.sqlite` where **7af0cde** is the container id of **bitcoin-abe**.

This copies the bitcoin-abe sqlite database to my local machine where I can open it up using a sqlite client like [Sqlite Manager for Firefox](https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/).

**Comment by c0achmcguirk** [comment]
Here's a screenshot of me using SQLite Manager for Firefox and opening up bitcoin-abe's sqlite database (abe.sqlite).

![abe sqlite](http://i.imgur.com/xybj0EN.png)

**Comment by c0achmcguirk** [comment]
Here is an overview of the setup I'm proposing. Maybe this will be helpful?

![overview](http://i.imgur.com/UglTj7f.png)

**Comment by c0achmcguirk** [comment]
Closing this issue.
